// ============================================================
// AI 工具导航数据
// 字段: id, name, desc(简短描述), url, category(分类 id), tags(关键词数组)
// 添加新工具：复制一个对象，改字段即可；分类 id 见下方 CATEGORIES
// ============================================================

const CATEGORIES = [
  { id: "chat",        name: "AI 聊天助手",   icon: "💬" },
  { id: "writing",     name: "文本 / 写作",   icon: "✍️" },
  { id: "image",       name: "图像生成",      icon: "🎨" },
  { id: "video",       name: "视频生成",      icon: "🎬" },
  { id: "audio",       name: "音频 / 音乐",   icon: "🎵" },
  { id: "code",        name: "代码开发",      icon: "💻" },
  { id: "design",      name: "设计 / UI",     icon: "🖌️" },
  { id: "agent",       name: "AI 智能体",     icon: "🤖" },
  { id: "opensource",  name: "开源模型",      icon: "🧠" },
  { id: "office",      name: "办公效率",      icon: "📊" },
  { id: "search",      name: "AI 搜索",       icon: "🔍" },
  { id: "browser",     name: "AI 浏览器",     icon: "🧭" },
  { id: "translate",   name: "翻译",          icon: "🌐" },
  { id: "edu",         name: "教育学习",      icon: "📚" },
  { id: "data",        name: "数据分析",      icon: "📈" },
  { id: "marketing",   name: "营销 / 商业",   icon: "📣" },
  { id: "3d",          name: "3D / 空间",     icon: "🧊" },
  { id: "world",       name: "世界模型",      icon: "🌍" },
  { id: "research",    name: "研究 / 科学",   icon: "🔬" },
  { id: "meeting",     name: "会议 / 笔记",   icon: "📝" },
  { id: "resume",      name: "简历 / 招聘",   icon: "👔" },
  { id: "podcast",     name: "播客 / 语音",   icon: "🎙️" },
  { id: "photo",       name: "图像处理",      icon: "🖼️" },
  { id: "ppt",         name: "PPT 制作",      icon: "📑" },
  { id: "digitalhuman",name: "AI 数字人",     icon: "👤" },
  { id: "input",       name: "AI 输入法",     icon: "⌨️" },
  { id: "gaming",      name: "游戏 / 娱乐",   icon: "🎮" },
  { id: "health",      name: "健康 / 医疗",   icon: "💊" },
  { id: "legal",       name: "法律",          icon: "⚖️" },
  { id: "finance",     name: "金融",          icon: "💰" },
  { id: "weather",     name: "天气 / 生活",   icon: "🌤️" },
  { id: "niche",       name: "垂直 / 小众",   icon: "✨" }
];

// ============================================================
// 工具数据（按分类组织）
// ============================================================
const TOOLS = [
  // ---------- AI 聊天助手 ----------
  { name: "ChatGPT",         desc: "OpenAI 出品的对话式 AI，多模态能力强",     url: "https://chat.openai.com",        category: "chat",  tags: ["openai","gpt","对话","多模态"] },
  { name: "Claude",          desc: "Anthropic 出品，长文档理解与写作见长",      url: "https://claude.ai",              category: "chat",  tags: ["anthropic","claude","长文本","写作"] },
  { name: "Gemini",          desc: "Google 多模态 AI，深度整合 Workspace",      url: "https://gemini.google.com",      category: "chat",  tags: ["google","gemini","多模态","bard"] },
  { name: "Grok",            desc: "xAI 出品，X 平台内置，实时联网",            url: "https://grok.com",               category: "chat",  tags: ["xai","马斯克","twitter","联网"] },
  { name: "DeepSeek",        desc: "国产开源大模型，推理能力强",                url: "https://chat.deepseek.com",      category: "chat",  tags: ["深度求索","国产","开源","推理"] },
  { name: "通义千问",        desc: "阿里通义大模型",                            url: "https://tongyi.aliyun.com",      category: "chat",  tags: ["阿里","qwen","国产"] },
  { name: "文心一言",        desc: "百度文心大模型",                            url: "https://yiyan.baidu.com",        category: "chat",  tags: ["百度","文心","国产"] },
  { name: "Kimi",            desc: "月之暗面出品，长文本处理专家",              url: "https://kimi.moonshot.cn",       category: "chat",  tags: ["月之暗面","长文本","国产"] },
  { name: "豆包",            desc: "字节跳动旗下 AI 助手",                       url: "https://www.doubao.com",         category: "chat",  tags: ["字节","抖音","国产"] },
  { name: "智谱清言",        desc: "智谱 AI 出品的对话助手",                    url: "https://chatglm.cn",             category: "chat",  tags: ["智谱","glm","国产"] },
  { name: "Perplexity",      desc: "AI 答案引擎，带引用来源",                   url: "https://www.perplexity.ai",     category: "chat",  tags: ["搜索","答案","引用"] },
  { name: "Mistral Chat",    desc: "Mistral 官方聊天界面",                      url: "https://chat.mistral.ai",        category: "chat",  tags: ["mistral","欧洲","开源"] },
  { name: "Poe",             desc: "Quora 出品的 AI 多模型聚合平台",            url: "https://poe.com",                category: "chat",  tags: ["quora","多模型","聚合"] },
  { name: "HuggingChat",     desc: "HuggingFace 官方聊天界面，开源模型多",      url: "https://huggingface.co/chat",    category: "chat",  tags: ["huggingface","开源","免费"] },
  { name: "You.com",         desc: "AI 搜索 + 聊天",                            url: "https://you.com",                category: "chat",  tags: ["搜索","聊天"] },
  { name: "Copilot",         desc: "微软 Copilot，多模型驱动",                  url: "https://copilot.microsoft.com",  category: "chat",  tags: ["微软","bing","gpt4"] },
  { name: "Le Chat",         desc: "Mistral 出品的聊天助手",                    url: "https://chat.mistral.ai",        category: "chat",  tags: ["mistral"] },
  { name: "元宝",            desc: "腾讯混元大模型对话产品",                    url: "https://yuanbao.tencent.com",    category: "chat",  tags: ["腾讯","混元","国产"] },
  { name: "百川",            desc: "百川智能大模型",                            url: "https://www.baichuan.com",       category: "chat",  tags: ["王小川","国产"] },
  { name: "MiniMax 海螺 AI",   desc: "MiniMax 旗下对话产品",                       url: "https://hailuoai.com",           category: "chat",  tags: ["minimax","海螺","国产"] },

  // ---------- 文本 / 写作 ----------
  { name: "Notion AI",       desc: "Notion 内置 AI，写笔记/总结",               url: "https://www.notion.so/product/ai", category: "writing", tags: ["笔记","总结","notion"] },
  { name: "Grammarly",       desc: "英文写作纠错与润色",                        url: "https://www.grammarly.com",      category: "writing", tags: ["英语","语法","纠错"] },
  { name: "秘塔写作猫",      desc: "国产 AI 写作助手",                          url: "https://xiezuocat.com",          category: "writing", tags: ["写作","国产"] },
  { name: "Jasper",          desc: "营销文案生成老牌工具",                      url: "https://www.jasper.ai",          category: "writing", tags: ["营销","文案","jasper"] },
  { name: "Copy.ai",         desc: "营销文案 / 销售邮件生成",                   url: "https://www.copy.ai",            category: "writing", tags: ["营销","邮件","文案"] },
  { name: "Rytr",            desc: "平价 AI 写作助手",                          url: "https://rytr.me",                category: "writing", tags: ["写作","便宜"] },
  { name: "Writesonic",      desc: "SEO / 博客 / 广告文案",                     url: "https://writesonic.com",         category: "writing", tags: ["seo","博客","广告"] },
  { name: "Sudowrite",       desc: "小说创作专用",                              url: "https://www.sudowrite.com",      category: "writing", tags: ["小说","创作","故事"] },
  { name: "Lex",             desc: "简洁优雅的 AI 写作工具",                    url: "https://lex.page",               category: "writing", tags: ["写作","极简"] },
  { name: "Hemingway",       desc: "可读性检查器",                              url: "https://hemingwayapp.com",       category: "writing", tags: ["可读性","英文"] },
  { name: "Wordtune",        desc: "句子改写 / 润色",                           url: "https://www.wordtune.com",       category: "writing", tags: ["改写","润色"] },
  { name: "QuillBot",        desc: "改写 / 摘要 / 引用",                        url: "https://quillbot.com",           category: "writing", tags: ["改写","摘要","引用"] },
  { name: "Anyword",         desc: "营销文案效果预测",                          url: "https://anyword.com",            category: "writing", tags: ["营销","预测"] },
  { name: "Writer",          desc: "企业级 AI 写作平台",                        url: "https://writer.com",             category: "writing", tags: ["企业","合规"] },
  { name: "ContentShake AI", desc: "Semrush 出品，SEO 写作",                    url: "https://www.semrush.com",        category: "writing", tags: ["semrush","seo"] },
  { name: "Compose AI",      desc: "Chrome 插件，自动补全",                     url: "https://www.compose.ai",         category: "writing", tags: ["chrome","补全"] },
  { name: "AI Writer",       desc: "长文自动生成",                              url: "https://ai-writer.com",          category: "writing", tags: ["长文","seo"] },
  { name: "Writecream",      desc: "冷邮件 / 销售信生成",                       url: "https://www.writecream.com",     category: "writing", tags: ["邮件","销售"] },
  { name: "Hypotenuse AI",   desc: "电商文案批量生成",                          url: "https://www.hypotenuse.ai",      category: "writing", tags: ["电商","批量"] },
  { name: "INK Editor",      desc: "AI + SEO 一体化写作",                       url: "https://inkforall.com",          category: "writing", tags: ["seo","ink"] },

  // ---------- 图像生成 ----------
  { name: "Midjourney",      desc: "顶级 AI 绘画工具，画质惊艳",                url: "https://www.midjourney.com",     category: "image", tags: ["绘画","艺术","顶级"] },
  { name: "DALL·E 3",        desc: "OpenAI 出品，文生图强",                     url: "https://openai.com/dall-e-3",    category: "image", tags: ["openai","dalle","文生图"] },
  { name: "Stable Diffusion", desc: "开源文生图模型，可本地部署",               url: "https://stability.ai",           category: "image", tags: ["开源","stability","本地"] },
  { name: "Leonardo.ai",     desc: "游戏 / 角色 / 概念设计",                    url: "https://leonardo.ai",            category: "image", tags: ["游戏","角色","设计"] },
  { name: "Adobe Firefly",   desc: "Adobe 官方 AI 图像生成",                    url: "https://firefly.adobe.com",      category: "image", tags: ["adobe","ps","商用"] },
  { name: "Ideogram",        desc: "强项是文字渲染",                            url: "https://ideogram.ai",            category: "image", tags: ["文字","海报"] },
  { name: "Playground AI",   desc: "免费图像生成",                              url: "https://playground.com",         category: "image", tags: ["免费","sd"] },
  { name: "Lexica",          desc: "Stable Diffusion 搜索 + 生成",              url: "https://lexica.art",             category: "image", tags: ["搜索","sd"] },
  { name: "Civitai",         desc: "开源模型 / LoRA 社区",                      url: "https://civitai.com",            category: "image", tags: ["lora","社区","模型"] },
  { name: "SeaArt",          desc: "国产 AI 绘画平台",                          url: "https://www.seaart.ai",          category: "image", tags: ["国产","绘画"] },
  { name: "通义万相",        desc: "阿里 AI 绘画",                              url: "https://wanxiang.aliyun.com",    category: "image", tags: ["阿里","国产"] },
  { name: "文心一格",        desc: "百度 AI 绘画",                              url: "https://yige.baidu.com",         category: "image", tags: ["百度","国产"] },
  { name: "即梦 AI",         desc: "字节 AI 绘画",                              url: "https://jimeng.jianying.com",    category: "image", tags: ["字节","国产"] },
  { name: "Whee",            desc: "美图 AI 绘画",                              url: "https://www.whee.com",           category: "image", tags: ["美图","国产"] },
  { name: "Recraft",         desc: "矢量图 / 图标设计",                         url: "https://www.recraft.ai",         category: "image", tags: ["矢量","图标"] },
  { name: "Krea.ai",         desc: "实时 AI 绘画",                              url: "https://www.krea.ai",            category: "image", tags: ["实时","绘画"] },
  { name: "Bing Image Creator", desc: "微软 DALL·E 3 图像生成",                  url: "https://www.bing.com/images/create", category: "image", tags: ["微软","dalle","免费"] },
  { name: "Tensor.Art",      desc: "在线 SD 模型运行",                          url: "https://tensor.art",             category: "image", tags: ["sd","在线"] },
  { name: "NightCafe",       desc: "AI 艺术创作社区",                            url: "https://creator.nightcafe.studio", category: "image", tags: ["社区","艺术"] },
  { name: "Bing Create",     desc: "Bing 文生图",                               url: "https://www.bing.com/images/create", category: "image", tags: ["微软","免费"] },

  // ---------- 视频生成 ----------
  { name: "Sora",            desc: "OpenAI 视频生成",                           url: "https://openai.com/sora",        category: "video", tags: ["openai","sora","视频"] },
  { name: "Runway",          desc: "Gen-2/Gen-3 视频生成",                      url: "https://runwayml.com",           category: "video", tags: ["runway","gen3","视频"] },
  { name: "Pika",            desc: "短小视频生成神器",                          url: "https://pika.art",               category: "video", tags: ["pika","短视频"] },
  { name: "Luma Dream Machine", desc: "Luma 视频生成",                          url: "https://lumalabs.ai",            category: "video", tags: ["luma","视频"] },
  { name: "Kling",           desc: "快手可灵视频生成",                          url: "https://klingai.com",            category: "video", tags: ["快手","国产","可灵"] },
  { name: "Vidu",            desc: "生数科技视频生成",                          url: "https://www.vidu.studio",        category: "video", tags: ["国产","生数"] },
  { name: "Hailuo",          desc: "MiniMax 视频生成",                            url: "https://hailuoai.com/video",     category: "video", tags: ["minimax","海螺","国产"] },
  { name: "HeyGen",          desc: "数字人 / 视频翻译",                         url: "https://www.heygen.com",         category: "video", tags: ["数字人","翻译"] },
  { name: "Synthesia",       desc: "AI 数字人视频",                             url: "https://www.synthesia.io",       category: "video", tags: ["数字人","企业"] },
  { name: "D-ID",            desc: "照片转数字人",                              url: "https://www.d-id.com",           category: "video", tags: ["数字人","照片"] },
  { name: "Descript",        desc: "视频剪辑 + AI",                             url: "https://www.descript.com",       category: "video", tags: ["剪辑","字幕"] },
  { name: "OpusClip",        desc: "长视频自动剪短",                            url: "https://www.opus.pro",           category: "video", tags: ["剪辑","短视频"] },
  { name: "CapCut",         desc: "剪映国际版，AI 剪辑",                       url: "https://www.capcut.com",         category: "video", tags: ["字节","剪辑","国产"] },
  { name: "InVideo",         desc: "AI 视频生成",                               url: "https://invideo.io",             category: "video", tags: ["视频","模板"] },
  { name: "Pictory",         desc: "文转视频",                                  url: "https://pictory.ai",             category: "video", tags: ["文转视频"] },
  { name: "Synthesys",       desc: "AI 配音 / 数字人",                          url: "https://synthesys.io",           category: "video", tags: ["配音","数字人"] },
  { name: "Veed.io",         desc: "在线视频编辑 + AI",                         url: "https://www.veed.io",            category: "video", tags: ["剪辑","字幕"] },
  { name: "Steve AI",        desc: "动画视频生成",                              url: "https://www.steve.ai",           category: "video", tags: ["动画"] },
  { name: "Lumen5",          desc: "博客转视频",                                url: "https://lumen5.com",             category: "video", tags: ["博客","转视频"] },
  { name: "Fliki",           desc: "文案转带配音视频",                          url: "https://fliki.ai",               category: "video", tags: ["配音","文案"] },

  // ---------- 音频 / 音乐 ----------
  { name: "Suno",            desc: "AI 音乐生成",                               url: "https://www.suno.ai",            category: "audio", tags: ["音乐","suno","作曲"] },
  { name: "Udio",            desc: "AI 音乐生成",                               url: "https://www.udio.com",           category: "audio", tags: ["音乐","作曲"] },
  { name: "ElevenLabs",      desc: "顶级 AI 配音",                              url: "https://elevenlabs.io",          category: "audio", tags: ["配音","克隆","语音"] },
  { name: "Murf",            desc: "AI 配音 / 数字人",                          url: "https://murf.ai",                category: "audio", tags: ["配音","数字人"] },
  { name: "Play.ht",         desc: "AI 配音",                                   url: "https://play.ht",                category: "audio", tags: ["配音"] },
  { name: "LOVO AI",         desc: "AI 配音",                                   url: "https://lovo.ai",                category: "audio", tags: ["配音"] },
  { name: "AIVA",            desc: "AI 作曲",                                   url: "https://www.aiva.ai",            category: "audio", tags: ["作曲","aiva"] },
  { name: "Soundraw",        desc: "AI 背景音乐",                               url: "https://soundraw.io",            category: "audio", tags: ["背景音乐"] },
  { name: "Boomy",           desc: "小白也能做歌",                              url: "https://boomy.com",              category: "audio", tags: ["作曲","入门"] },
  { name: "Stable Audio",    desc: "Stability AI 音乐生成",                     url: "https://stableaudio.com",        category: "audio", tags: ["stability","音乐"] },
  { name: "BGM 猫",          desc: "国产 AI 背景音乐",                          url: "https://www.bgmcat.com",         category: "audio", tags: ["国产","配乐"] },
  { name: "网易天音",        desc: "网易 AI 音乐",                              url: "https://tianyin.music.163.com",  category: "audio", tags: ["网易","国产"] },
  { name: "Resemble AI",     desc: "声音克隆",                                  url: "https://www.resemble.ai",        category: "audio", tags: ["克隆","声音"] },
  { name: "WellSaid Labs",   desc: "企业级配音",                                url: "https://wellsaidlabs.com",       category: "audio", tags: ["配音","企业"] },
  { name: "Replica Studios", desc: "游戏 / 影视配音",                           url: "https://replicastudios.com",     category: "audio", tags: ["游戏","配音"] },

  // ---------- 代码开发 ----------
  { name: "GitHub Copilot",  desc: "GitHub + OpenAI 的 AI 结对编程",            url: "https://github.com/features/copilot", category: "code", tags: ["github","结对","ide"] },
  { name: "Cursor",          desc: "AI 优先的代码编辑器",                       url: "https://www.cursor.com",         category: "code", tags: ["编辑器","ide","ai"] },
  { name: "Claude Code",     desc: "Anthropic 推出的终端 AI 编程",              url: "https://www.anthropic.com/claude-code", category: "code", tags: ["anthropic","终端","编程"] },
  { name: "Windsurf",        desc: "Codeium 推出的 AI IDE",                     url: "https://codeium.com/windsurf",   category: "code", tags: ["codeium","ide"] },
  { name: "Codeium",         desc: "免费 AI 代码补全",                          url: "https://codeium.com",            category: "code", tags: ["免费","补全"] },
  { name: "Tabnine",         desc: "本地 AI 代码补全",                          url: "https://www.tabnine.com",        category: "code", tags: ["补全","本地"] },
  { name: "Replit Ghost",    desc: "Replit AI 编程",                            url: "https://replit.com",             category: "code", tags: ["replit","在线"] },
  { name: "v0.dev",          desc: "Vercel 出品，UI → 代码",                    url: "https://v0.dev",                 category: "code", tags: ["vercel","ui","前端"] },
  { name: "Bolt.new",        desc: "StackBlitz AI 全栈生成",                    url: "https://bolt.new",               category: "code", tags: ["全栈","web"] },
  { name: "Lovable",         desc: "AI 全栈 Web 生成",                          url: "https://lovable.dev",            category: "code", tags: ["全栈","web"] },
  { name: "Cody",            desc: "Sourcegraph AI 编程助手",                   url: "https://sourcegraph.com/cody",   category: "code", tags: ["sourcegraph","企业"] },
  { name: "Continue",        desc: "开源 AI 编程助手",                          url: "https://www.continue.dev",       category: "code", tags: ["开源","ide"] },
  { name: "Aider",           desc: "终端 AI 结对编程",                          url: "https://aider.chat",             category: "code", tags: ["终端","开源"] },
  { name: "Cline",           desc: "VSCode AI 代理",                            url: "https://github.com/cline/cline", category: "code", tags: ["vscode","代理"] },
  { name: "Phind",           desc: "面向开发者的 AI 搜索",                      url: "https://www.phind.com",          category: "code", tags: ["搜索","开发者"] },
  { name: "MarsX",           desc: "AI 应用生成",                               url: "https://marsx.dev",              category: "code", tags: ["无代码","应用"] },
  { name: "Devin",           desc: "Cognition 推出的 AI 软件工程师",            url: "https://www.cognition.ai",       category: "code", tags: ["agent","devin"] },
  { name: "通义灵码",        desc: "阿里 AI 编程助手",                          url: "https://lingma.aliyun.com",      category: "code", tags: ["阿里","国产"] },
  { name: "CodeGeeX",        desc: "智谱 AI 编程",                              url: "https://codegeex.cn",            category: "code", tags: ["智谱","国产"] },
  { name: "豆包 MarsCode",   desc: "字节 AI 编程",                              url: "https://www.marscode.com",       category: "code", tags: ["字节","国产"] },

  // ---------- 设计 / UI ----------
  { name: "Figma AI",        desc: "Figma 内置 AI 功能",                        url: "https://www.figma.com",          category: "design", tags: ["figma","ui"] },
  { name: "Galileo AI",      desc: "AI 生成 UI 设计",                           url: "https://www.usegalileo.ai",     category: "design", tags: ["ui","生成"] },
  { name: "Uizard",          desc: "截图 / 草图转 UI",                          url: "https://uizard.io",              category: "design", tags: ["ui","草图"] },
  { name: "Visily",          desc: "草图 / 截图转 UI",                          url: "https://www.visily.ai",          category: "design", tags: ["草图","ui"] },
  { name: "Magician for Figma", desc: "Figma 插件 AI 设计",                     url: "https://magician.design",        category: "design", tags: ["figma","插件"] },
  { name: "Microsoft Designer", desc: "微软 AI 设计工具",                       url: "https://designer.microsoft.com", category: "design", tags: ["微软","海报"] },
  { name: "Canva AI",        desc: "Canva AI 套件",                             url: "https://www.canva.com",          category: "design", tags: ["canva","设计"] },
  { name: "Looka",           desc: "AI Logo 生成",                              url: "https://looka.com",              category: "design", tags: ["logo","品牌"] },
  { name: "Brandmark",       desc: "AI 品牌设计",                               url: "https://brandmark.io",           category: "design", tags: ["品牌","logo"] },
  { name: "Khroma",          desc: "AI 配色",                                   url: "https://www.khroma.co",          category: "design", tags: ["配色"] },
  { name: "Colormind",       desc: "AI 配色",                                   url: "http://colormind.io",            category: "design", tags: ["配色"] },
  { name: "Framer AI",       desc: "AI 建站",                                   url: "https://www.framer.com/ai",      category: "design", tags: ["建站","framer"] },
  { name: "Dora",            desc: "AI 3D 网站",                                url: "https://www.dora.run",           category: "design", tags: ["3d","建站"] },
  { name: "Relume",          desc: "AI 帮你搭线框图",                           url: "https://www.relume.io",          category: "design", tags: ["线框图","figma"] },
  { name: "Mockplus",        desc: "AI 原型工具",                               url: "https://www.mockplus.com",       category: "design", tags: ["原型"] },

  // ---------- 办公效率 ----------
  { name: "Microsoft 365 Copilot", desc: "Office 全家桶 AI 助手",               url: "https://www.microsoft.com/microsoft-365/copilot", category: "office", tags: ["微软","office","ppt"] },
  { name: "Google Workspace AI", desc: "谷歌全家桶 AI 集成",                    url: "https://workspace.google.com",   category: "office", tags: ["谷歌","docs"] },
  { name: "Notion",          desc: "笔记 / 知识库",                             url: "https://www.notion.so",          category: "office", tags: ["笔记","协作"] },
  { name: "Coda",            desc: "AI 文档协作",                               url: "https://coda.io",                category: "office", tags: ["文档","协作"] },
  { name: "ClickUp AI",      desc: "项目管理 + AI",                             url: "https://clickup.com",            category: "office", tags: ["项目","管理"] },
  { name: "Asana AI",        desc: "任务管理 + AI",                             url: "https://asana.com",             category: "office", tags: ["任务","管理"] },
  { name: "Mem",             desc: "AI 笔记，自动归类",                        url: "https://mem.ai",                 category: "office", tags: ["笔记","自动"] },
  { name: "Reflect",         desc: "AI 笔记 + 日程",                            url: "https://reflect.app",            category: "office", tags: ["笔记","日程"] },
  { name: "Reclaim",         desc: "AI 日程管理",                               url: "https://reclaim.ai",             category: "office", tags: ["日程","效率"] },
  { name: "Motion",          desc: "AI 日程 + 任务",                            url: "https://www.usemotion.com",      category: "office", tags: ["日程","任务"] },
  { name: "飞书智能伙伴",    desc: "字节飞书 AI 助手",                          url: "https://www.feishu.cn",          category: "office", tags: ["飞书","国产"] },
  { name: "钉钉斜杠",        desc: "钉钉 AI 助手",                              url: "https://www.dingtalk.com",       category: "office", tags: ["钉钉","国产"] },
  { name: "腾讯文档 AI",     desc: "腾讯文档 AI 能力",                          url: "https://docs.qq.com",            category: "office", tags: ["腾讯","国产"] },
  { name: "WPS AI",          desc: "WPS AI 助手",                               url: "https://www.wps.cn",             category: "office", tags: ["wps","国产"] },
  { name: "Zapier",          desc: "AI 自动化工作流",                           url: "https://zapier.com",             category: "office", tags: ["自动化","工作流"] },
  { name: "Make",            desc: "可视化自动化 + AI",                         url: "https://make.com",               category: "office", tags: ["自动化","工作流"] },
  { name: "Bardeen",         desc: "浏览器自动化",                              url: "https://www.bardeen.ai",         category: "office", tags: ["自动化","浏览器"] },
  { name: "Tactiq",          desc: "会议转录",                                  url: "https://tactiq.io",              category: "office", tags: ["会议","转录"] },

  // ---------- AI 搜索 ----------
  { name: "Perplexity AI",   desc: "AI 答案引擎",                               url: "https://www.perplexity.ai",     category: "search", tags: ["答案","引用"] },
  { name: "You.com",         desc: "AI 搜索",                                   url: "https://you.com",                category: "search", tags: ["搜索"] },
  { name: "Phind",           desc: "开发者搜索",                                url: "https://www.phind.com",          category: "search", tags: ["开发者"] },
  { name: "Komo",            desc: "AI 搜索 + 聊天",                            url: "https://komo.ai",                category: "search", tags: ["搜索"] },
  { name: "iAsk",            desc: "免费 AI 搜索",                              url: "https://iask.ai",                category: "search", tags: ["免费","搜索"] },
  { name: "Andi",            desc: "对话式搜索",                                url: "https://andisearch.com",         category: "search", tags: ["搜索","对话"] },
  { name: "Exa",             desc: "神经搜索 API",                              url: "https://exa.ai",                 category: "search", tags: ["api","搜索"] },
  { name: "Brave Search",    desc: "隐私 + AI",                                 url: "https://search.brave.com",       category: "search", tags: ["隐私","搜索"] },
  { name: "Kagi",            desc: "付费无广告搜索 + AI",                       url: "https://kagi.com",               category: "search", tags: ["付费","无广告"] },
  { name: "秘塔 AI 搜索",    desc: "国产 AI 搜索",                              url: "https://metaso.cn",              category: "search", tags: ["国产","搜索"] },
  { name: "360AI 搜索",      desc: "360 AI 搜索",                               url: "https://www.sou.com",            category: "search", tags: ["360","国产"] },
  { name: "纳米 AI 搜索",    desc: "360 旗下",                                  url: "https://www.n.cn",               category: "search", tags: ["360","国产"] },

  // ---------- 翻译 ----------
  { name: "DeepL",           desc: "公认最准的 AI 翻译",                        url: "https://www.deepl.com",          category: "translate", tags: ["翻译","准确"] },
  { name: "Google Translate", desc: "谷歌翻译",                                  url: "https://translate.google.com",   category: "translate", tags: ["谷歌","免费"] },
  { name: "微软翻译",        desc: "微软翻译",                                  url: "https://www.bing.com/translator", category: "translate", tags: ["微软"] },
  { name: "沉浸式翻译",      desc: "双语对照网页翻译",                          url: "https://immersivetranslate.com", category: "translate", tags: ["双语","插件","国产"] },
  { name: "火山翻译",        desc: "字节翻译",                                  url: "https://translate.volcengine.com", category: "translate", tags: ["字节","国产"] },
  { name: "百度翻译",        desc: "百度翻译",                                  url: "https://fanyi.baidu.com",        category: "translate", tags: ["百度","国产"] },
  { name: "腾讯翻译君",      desc: "腾讯翻译",                                  url: "https://transmart.qq.com",       category: "translate", tags: ["腾讯","国产"] },
  { name: "彩云小译",        desc: "中英翻译 + 浏览器插件",                     url: "https://fanyi.caiyunapp.com",    category: "translate", tags: ["插件","国产"] },
  { name: "Reverso",         desc: "翻译 + 例句",                                url: "https://www.reverso.net",        category: "translate", tags: ["翻译","例句"] },
  { name: "Linguee",         desc: "双语例句搜索",                              url: "https://www.linguee.com",        category: "translate", tags: ["例句"] },
  { name: "Lingvanex",       desc: "多语言翻译",                                url: "https://lingvanex.com",          category: "translate", tags: ["多语言"] },
  { name: "Heygen Translate", desc: "视频口型翻译",                             url: "https://www.heygen.com",         category: "translate", tags: ["视频","口型"] },

  // ---------- 教育学习 ----------
  { name: "Khanmigo",        desc: "可汗学院 AI 导师",                          url: "https://www.khanacademy.org/khan-labs", category: "edu", tags: ["khan","导师"] },
  { name: "Photomath",       desc: "拍照解题",                                  url: "https://photomath.com",          category: "edu", tags: ["数学","拍照"] },
  { name: "Mathly",          desc: "AI 数学辅导",                               url: "https://mathly.me",              category: "edu", tags: ["数学"] },
  { name: "Curipod",         desc: "AI 互动课堂",                               url: "https://curipod.com",            category: "edu", tags: ["课堂"] },
  { name: "Quizizz AI",      desc: "AI 出题",                                   url: "https://quizizz.com",            category: "edu", tags: ["测验"] },
  { name: "MagicSchool",     desc: "教师 AI 助手",                              url: "https://www.magicschool.ai",     category: "edu", tags: ["教师"] },
  { name: "Eduaide.ai",      desc: "教师备课 AI",                               url: "https://www.eduaide.ai",         category: "edu", tags: ["教师"] },
  { name: "Socratic",        desc: "Google 学习助手",                           url: "https://socratic.org",           category: "edu", tags: ["谷歌"] },
  { name: "Duolingo Max",    desc: "Duolingo AI 口语",                          url: "https://www.duolingo.com",       category: "edu", tags: ["语言","口语"] },
  { name: "Speak",           desc: "AI 口语陪练",                               url: "https://www.speak.com",          category: "edu", tags: ["口语","英语"] },
  { name: "Elsa Speak",      desc: "AI 英语发音",                               url: "https://elsaspeak.com",          category: "edu", tags: ["发音"] },
  { name: "Quizlet",         desc: "AI 学习卡片",                               url: "https://quizlet.com",            category: "edu", tags: ["卡片"] },
  { name: "Course Hero",     desc: "AI 学习资源",                               url: "https://www.coursehero.com",     category: "edu", tags: ["资源"] },
  { name: "Studyfetch",      desc: "AI 闪卡 / 测验",                            url: "https://www.studyfetch.com",     category: "edu", tags: ["闪卡"] },
  { name: "Scholarcy",       desc: "AI 论文总结",                               url: "https://www.scholarcy.com",      category: "edu", tags: ["论文"] },

  // ---------- 数据分析 ----------
  { name: "Julius AI",       desc: "对话式数据分析",                            url: "https://julius.ai",              category: "data", tags: ["数据","分析"] },
  { name: "DataRobot",       desc: "企业级 AI 建模",                            url: "https://www.datarobot.com",      category: "data", tags: ["企业","建模"] },
  { name: "H2O.ai",          desc: "开源 AI 平台",                              url: "https://h2o.ai",                 category: "data", tags: ["开源","企业"] },
  { name: "Obviously AI",    desc: "无代码机器学习",                            url: "https://www.obviously.ai",       category: "data", tags: ["无代码","ml"] },
  { name: "Akkio",           desc: "无代码 AI",                                 url: "https://www.akkio.com",          category: "data", tags: ["无代码"] },
  { name: "Polymer",         desc: "AI 转数据看板",                             url: "https://www.polymersearch.com",  category: "data", tags: ["看板"] },
  { name: "Vizly",           desc: "AI 数据可视化",                             url: "https://vizly.fly.dev",          category: "data", tags: ["可视化"] },
  { name: "ChatCSV",         desc: "对话式 CSV 分析",                           url: "https://www.chatcsv.co",         category: "data", tags: ["csv"] },
  { name: "AskYourDatabase", desc: "自然语言 SQL",                              url: "https://www.askyourdatabase.com", category: "data", tags: ["sql"] },
  { name: "Tableau AI",      desc: "Tableau AI 功能",                           url: "https://www.tableau.com",        category: "data", tags: ["tableau","可视化"] },
  { name: "Power BI Copilot", desc: "微软 BI AI",                               url: "https://powerbi.microsoft.com",  category: "data", tags: ["微软","bi"] },

  // ---------- 营销 / 商业 ----------
  { name: "Surfer SEO",      desc: "AI SEO 优化",                               url: "https://surferseo.com",          category: "marketing", tags: ["seo"] },
  { name: "Frase",           desc: "AI 内容 + SEO",                             url: "https://www.frase.io",           category: "marketing", tags: ["seo","内容"] },
  { name: "MarketMuse",      desc: "内容策略 AI",                               url: "https://www.marketmuse.com",     category: "marketing", tags: ["内容","策略"] },
  { name: "AdCreative.ai",   desc: "AI 广告素材",                               url: "https://www.adcreative.ai",      category: "marketing", tags: ["广告"] },
  { name: "Persado",         desc: "AI 文案优化",                               url: "https://www.persado.com",        category: "marketing", tags: ["文案"] },
  { name: "Smartwriter",     desc: "AI 冷邮件",                                 url: "https://www.smartwriter.ai",     category: "marketing", tags: ["邮件"] },
  { name: "InstaText",       desc: "AI 文案润色",                               url: "https://instatext.io",           category: "marketing", tags: ["润色"] },
  { name: "Brandwatch",      desc: "社媒 AI 监测",                              url: "https://www.brandwatch.com",     category: "marketing", tags: ["社媒"] },
  { name: "Lately",          desc: "AI 社媒内容",                               url: "https://www.lately.ai",          category: "marketing", tags: ["社媒"] },
  { name: "Predis.ai",       desc: "AI 社媒生成",                               url: "https://predis.ai",              category: "marketing", tags: ["社媒"] },

  // ---------- 3D 建模 ----------
  { name: "Tripo3D",         desc: "AI 3D 建模",                                url: "https://www.tripo3d.ai",         category: "3d", tags: ["3d","建模"] },
  { name: "Meshy",           desc: "文/图转 3D",                                url: "https://www.meshy.ai",           category: "3d", tags: ["3d","文转3d"] },
  { name: "Luma Genie",      desc: "文本生成 3D",                               url: "https://lumalabs.ai",            category: "3d", tags: ["3d","luma"] },
  { name: "Sloyd",           desc: "AI 3D 建模",                                url: "https://www.sloyd.ai",           category: "3d", tags: ["3d"] },
  { name: "Kaedim",          desc: "2D 转 3D",                                  url: "https://www.kaedim.com",         category: "3d", tags: ["2d3d"] },
  { name: "Cascadeur",       desc: "AI 动作捕捉",                               url: "https://cascadeur.com",          category: "3d", tags: ["动作","动画"] },
  { name: "Plask",           desc: "AI 动作捕捉",                               url: "https://plask.ai",               category: "3d", tags: ["动作"] },
  { name: "CSM",             desc: "图转 3D",                                   url: "https://csm.ai",                 category: "3d", tags: ["图转3d"] },

  // ---------- 研究 / 科学 ----------
  { name: "Elicit",          desc: "AI 文献研究",                               url: "https://elicit.com",             category: "research", tags: ["论文","研究"] },
  { name: "Consensus",       desc: "AI 学术搜索",                               url: "https://consensus.app",          category: "research", tags: ["学术","搜索"] },
  { name: "SciSpace",        desc: "AI 论文阅读",                               url: "https://typeset.io",             category: "research", tags: ["论文"] },
  { name: "Research Rabbit", desc: "AI 文献网络",                               url: "https://www.researchrabbit.ai",  category: "research", tags: ["文献"] },
  { name: "Scite",           desc: "AI 引用分析",                               url: "https://scite.ai",               category: "research", tags: ["引用"] },
  { name: "Iris.ai",         desc: "AI 科研引擎",                               url: "https://iris.ai",                category: "research", tags: ["科研"] },
  { name: "Scholarcy",       desc: "AI 论文总结",                               url: "https://www.scholarcy.com",      category: "research", tags: ["总结"] },
  { name: "Semantic Scholar", desc: "AI 学术搜索",                              url: "https://www.semanticscholar.org", category: "research", tags: ["学术"] },
  { name: "Connected Papers", desc: "论文关系图",                                url: "https://www.connectedpapers.com", category: "research", tags: ["图谱"] },
  { name: "Genei",           desc: "AI 研究助手",                               url: "https://www.genei.io",           category: "research", tags: ["研究"] },

  // ---------- AI 智能体 ----------
  { name: "AutoGPT",         desc: "开源自主 Agent 鼻祖",                       url: "https://agpt.co",                category: "agent", tags: ["agent","自主","开源"] },
  { name: "AgentGPT",        desc: "浏览器里跑 Agent",                          url: "https://agentgpt.reworkd.ai",    category: "agent", tags: ["agent"] },
  { name: "BabyAGI",         desc: "经典任务循环 Agent",                        url: "https://github.com/yoheinakajima/babyagi", category: "agent", tags: ["agent","开源"] },
  { name: "CrewAI",          desc: "多 Agent 协作框架",                         url: "https://www.crewai.com",         category: "agent", tags: ["agent","协作"] },
  { name: "LangGraph",       desc: "LangChain 推出的 Agent 框架",               url: "https://langchain.com/langgraph", category: "agent", tags: ["langchain","agent"] },
  { name: "n8n",             desc: "工作流 + AI 自动化",                        url: "https://n8n.io",                 category: "agent", tags: ["工作流","自动化"] },
  { name: "Flowise",         desc: "可视化 LLM 编排",                           url: "https://flowiseai.com",          category: "agent", tags: ["编排","可视化"] },
  { name: "Dust",            desc: "可定制 AI 助手平台",                        url: "https://dust.tt",                category: "agent", tags: ["助手"] },
  { name: "Fixpoint",        desc: "企业 AI 助手",                              url: "https://fixpoint.ai",            category: "agent", tags: ["企业"] },
  { name: "Devin",           desc: "Cognition AI 软件工程师",                   url: "https://www.cognition.ai",       category: "agent", tags: ["agent","devin"] },
  { name: "Manus",           desc: "通用 AI 代理",                              url: "https://manus.im",               category: "agent", tags: ["agent","国产"] },
  { name: "Skywork",         desc: "昆仑万维 Skywork Agent",                    url: "https://skywork.ai",             category: "agent", tags: ["agent","国产"] },

  // ---------- 开源模型 ----------
  { name: "Hugging Face",    desc: "开源模型/数据集社区",                       url: "https://huggingface.co",         category: "opensource", tags: ["开源","社区"] },
  { name: "Meta Llama",      desc: "Meta 开源大模型",                           url: "https://llama.meta.com",         category: "opensource", tags: ["meta","llama"] },
  { name: "Mistral",         desc: "Mistral 开源模型",                          url: "https://mistral.ai",             category: "opensource", tags: ["mistral","开源"] },
  { name: "Qwen",            desc: "阿里通义千问开源",                          url: "https://qwen.alibaba.com",       category: "opensource", tags: ["阿里","qwen"] },
  { name: "DeepSeek 开源",   desc: "DeepSeek 开源模型",                         url: "https://github.com/deepseek-ai", category: "opensource", tags: ["deepseek"] },
  { name: "GLM",             desc: "智谱 GLM 开源",                             url: "https://github.com/THUDM",       category: "opensource", tags: ["智谱","glm"] },
  { name: "Falcon",          desc: "TII 开源大模型",                            url: "https://falconllm.tii.ae",       category: "opensource", tags: ["falcon"] },
  { name: "Gemma",           desc: "Google 开源模型",                            url: "https://ai.google.dev/gemma",    category: "opensource", tags: ["google","gemma"] },
  { name: "Phi-3",           desc: "微软小型开源",                              url: "https://azure.microsoft.com/en-us/products/phi-3", category: "opensource", tags: ["微软","小型"] },
  { name: "Yi",              desc: "零一万物开源",                              url: "https://www.lingyiwanwu.com",    category: "opensource", tags: ["零一万物","国产"] },
  { name: "Baichuan",        desc: "百川开源",                                  url: "https://github.com/baichuan-inc", category: "opensource", tags: ["百川"] },
  { name: "Ollama",          desc: "本地运行开源模型",                          url: "https://ollama.com",             category: "opensource", tags: ["本地","运行"] },
  { name: "LM Studio",       desc: "本地 LLM 客户端",                           url: "https://lmstudio.ai",            category: "opensource", tags: ["本地","客户端"] },
  { name: "GPT4All",         desc: "本地跑模型",                                url: "https://www.nomic.ai/gpt4all",    category: "opensource", tags: ["本地"] },

  // ---------- 会议 / 效率 ----------
  { name: "Otter.ai",        desc: "会议转录 + AI 总结",                        url: "https://otter.ai",               category: "meeting", tags: ["会议","转录"] },
  { name: "Fireflies.ai",    desc: "会议记录 AI",                               url: "https://fireflies.ai",           category: "meeting", tags: ["会议"] },
  { name: "Fathom",          desc: "免费会议 AI",                               url: "https://fathom.video",           category: "meeting", tags: ["会议","免费"] },
  { name: "Read AI",         desc: "会议 + 邮件 AI",                            url: "https://www.read.ai",            category: "meeting", tags: ["会议"] },
  { name: "Avoma",           desc: "销售会议 AI",                               url: "https://www.avoma.com",          category: "meeting", tags: ["销售","会议"] },
  { name: "Krisp",           desc: "AI 降噪",                                   url: "https://krisp.ai",               category: "meeting", tags: ["降噪"] },
  { name: "tl;dv",           desc: "会议录制 + AI",                             url: "https://tldv.io",                category: "meeting", tags: ["录制"] },
  { name: "Nyota",           desc: "AI 会议助理",                               url: "https://www.nyota.ai",           category: "meeting", tags: ["会议"] },

  // ---------- 简历 / 招聘 ----------
  { name: "Rezi",            desc: "AI 简历",                                   url: "https://www.rezi.ai",            category: "resume", tags: ["简历"] },
  { name: "Kickresume",      desc: "AI 简历",                                   url: "https://www.kickresume.com",     category: "resume", tags: ["简历"] },
  { name: "Resume.io",       desc: "AI 简历生成",                               url: "https://resume.io",              category: "resume", tags: ["简历"] },
  { name: "Teal",            desc: "AI 简历 + 求职",                            url: "https://www.tealhq.com",         category: "resume", tags: ["求职"] },
  { name: "LoopCV",          desc: "AI 求职",                                   url: "https://loopcv.pro",             category: "resume", tags: ["求职"] },
  { name: "Jobscan",         desc: "简历匹配 ATS",                              url: "https://www.jobscan.co",         category: "resume", tags: ["ats","匹配"] },
  { name: "HireVue",         desc: "AI 面试",                                   url: "https://www.hirevue.com",        category: "resume", tags: ["面试"] },
  { name: "八股文 AI",       desc: "面试题 AI",                                 url: "https://www.baguwenai.com",      category: "resume", tags: ["面试","国产"] },

  // ---------- 播客 / 语音 ----------
  { name: "Podcastle",       desc: "AI 播客录制",                               url: "https://podcastle.ai",           category: "podcast", tags: ["播客"] },
  { name: "Descript",        desc: "播客编辑",                                  url: "https://www.descript.com",       category: "podcast", tags: ["播客","编辑"] },
  { name: "Spotify AI DJ",   desc: "Spotify AI DJ",                             url: "https://www.spotify.com",        category: "podcast", tags: ["音乐","dj"] },
  { name: "Adobe Podcast",   desc: "AI 播客增强",                               url: "https://podcast.adobe.com",      category: "podcast", tags: ["播客","adobe"] },
  { name: "Podsqueeze",      desc: "AI 播客生成内容",                           url: "https://podsqueeze.com",         category: "podcast", tags: ["播客"] },
  { name: "Swell AI",        desc: "AI 写播客稿",                               url: "https://www.swellai.com",        category: "podcast", tags: ["播客"] },
  { name: "NotebookLM",      desc: "Google 播客 AI",                            url: "https://notebooklm.google.com",  category: "podcast", tags: ["播客","谷歌"] },

  // ---------- 图像处理 ----------
  { name: "Remove.bg",       desc: "AI 抠图",                                   url: "https://www.remove.bg",          category: "photo", tags: ["抠图"] },
  { name: "Cleanup.pictures", desc: "擦除杂物",                                 url: "https://cleanup.pictures",       category: "photo", tags: ["擦除"] },
  { name: "Upscale.media",   desc: "AI 放大",                                   url: "https://www.upscale.media",      category: "photo", tags: ["放大"] },
  { name: "Let's Enhance",   desc: "AI 增强",                                   url: "https://letsenhance.io",         category: "photo", tags: ["增强"] },
  { name: "Topaz Gigapixel", desc: "图片无损放大",                              url: "https://www.topazlabs.com",      category: "photo", tags: ["放大","topaz"] },
  { name: "Magnific AI",     desc: "高清放大",                                  url: "https://magnific.ai",            category: "photo", tags: ["放大"] },
  { name: "Clipdrop",        desc: "Stability 图像工具",                        url: "https://clipdrop.co",            category: "photo", tags: ["工具","stability"] },
  { name: "Cutout Pro",      desc: "AI 图像编辑",                               url: "https://www.cutout.pro",         category: "photo", tags: ["编辑"] },
  { name: "Pixelcut",        desc: "AI 商品图",                                 url: "https://www.pixelcut.ai",        category: "photo", tags: ["商品图"] },
  { name: "PhotoRoom",       desc: "商品图 AI",                                 url: "https://www.photoroom.com",      category: "photo", tags: ["商品图"] },

  // ---------- PPT 制作 ----------
  { name: "Gamma",           desc: "AI 生成 PPT",                               url: "https://gamma.app",              category: "ppt", tags: ["ppt","生成"] },
  { name: "Tome",            desc: "AI 演示文稿",                               url: "https://tome.app",               category: "ppt", tags: ["演示"] },
  { name: "Beautiful.ai",    desc: "智能 PPT",                                  url: "https://www.beautiful.ai",       category: "ppt", tags: ["智能"] },
  { name: "Pitch",           desc: "协作 PPT",                                  url: "https://pitch.com",              category: "ppt", tags: ["协作"] },
  { name: "SlidesAI",        desc: "Google Slides AI",                          url: "https://www.slidesai.io",        category: "ppt", tags: ["slides"] },
  { name: "Plus AI",         desc: "Google Slides AI",                          url: "https://www.plusdocs.com",        category: "ppt", tags: ["slides"] },
  { name: "ChatPPT",         desc: "国产 AI PPT",                               url: "https://www.chat-ppt.com",       category: "ppt", tags: ["国产"] },
  { name: "讯飞智文",        desc: "讯飞 AI PPT",                               url: "https://zhiwen.xfyun.cn",        category: "ppt", tags: ["讯飞","国产"] },
  { name: "islide",          desc: "iSlide AI",                                 url: "https://www.islide.cc",          category: "ppt", tags: ["国产"] },
  { name: "AIPPT",           desc: "AI PPT 平台",                               url: "https://www.aippt.cn",           category: "ppt", tags: ["国产"] },

  // ---------- 游戏 / 娱乐 ----------
  { name: "Scenario",        desc: "AI 游戏美术",                               url: "https://www.scenario.com",       category: "gaming", tags: ["游戏","美术"] },
  { name: "Ludo.ai",         desc: "AI 游戏设计",                               url: "https://ludo.ai",                category: "gaming", tags: ["游戏","设计"] },
  { name: "Rosebud AI",      desc: "AI 游戏生成",                               url: "https://www.rosebud.ai",         category: "gaming", tags: ["游戏","生成"] },
  { name: "Layer",           desc: "AI 角色扮演",                               url: "https://www.layer.ai",           category: "gaming", tags: ["角色"] },
  { name: "Inworld",         desc: "NPC AI",                                    url: "https://www.inworld.ai",         category: "gaming", tags: ["npc"] },
  { name: "Hidden Door",     desc: "AI 故事游戏",                               url: "https://www.hiddendoor.com",     category: "gaming", tags: ["故事"] },
  { name: "Charstar AI",     desc: "AI 角色聊天",                               url: "https://charstar.ai",            category: "gaming", tags: ["角色","聊天"] },
  { name: "SpicyChat",       desc: "AI 角色对话",                               url: "https://spicychat.ai",           category: "gaming", tags: ["角色"] },
  { name: "Janitor AI",      desc: "AI 角色聊天",                               url: "https://janitorai.com",          category: "gaming", tags: ["角色"] },

  // ---------- 健康 / 医疗 ----------
  { name: "Ada Health",      desc: "AI 问诊",                                   url: "https://ada.com",                category: "health", tags: ["问诊"] },
  { name: "Babylon Health",  desc: "AI 健康咨询",                               url: "https://www.babylonhealth.com",  category: "health", tags: ["健康"] },
  { name: "K Health",        desc: "AI 医疗",                                   url: "https://khealth.com",            category: "health", tags: ["医疗"] },
  { name: "Docus.ai",        desc: "AI 医生",                                   url: "https://docus.ai",               category: "health", tags: ["医生"] },
  { name: "Glass Health",    desc: "AI 临床决策",                               url: "https://glass.health",           category: "health", tags: ["临床"] },
  { name: "Suki AI",         desc: "AI 医生助手",                               url: "https://www.suki.ai",            category: "health", tags: ["医生"] },
  { name: "Abridge",         desc: "医患对话 AI",                               url: "https://www.abridge.com",        category: "health", tags: ["对话"] },

  // ---------- 法律 ----------
  { name: "DoNotPay",        desc: "AI 律师",                                   url: "https://donotpay.com",           category: "legal", tags: ["律师"] },
  { name: "Harvey",          desc: "律师 AI 助手",                              url: "https://www.harvey.ai",          category: "legal", tags: ["律师"] },
  { name: "Spellbook",       desc: "AI 法律文书",                               url: "https://www.spellbook.legal",    category: "legal", tags: ["文书"] },
  { name: "Ironclad",        desc: "AI 合同",                                   url: "https://ironcladapp.com",        category: "legal", tags: ["合同"] },
  { name: "Luminance",       desc: "AI 法律文档",                               url: "https://www.luminance.com",      category: "legal", tags: ["文档"] },
  { name: "Casetext",        desc: "AI 法律研究",                               url: "https://casetext.com",           category: "legal", tags: ["研究"] },

  // ---------- 金融 ----------
  { name: "Bloomberg GPT",   desc: "彭博金融 AI",                               url: "https://www.bloomberg.com",      category: "finance", tags: ["金融"] },
  { name: "Kensho",          desc: "金融 AI 分析",                              url: "https://kensho.com",             category: "finance", tags: ["分析"] },
  { name: "Alpaca",          desc: "AI 量化交易",                               url: "https://alpaca.markets",         category: "finance", tags: ["量化"] },
  { name: "Clearpool",       desc: "AI 信用评估",                               url: "https://clearpool.finance",      category: "finance", tags: ["信用"] },
  { name: "Stampli",         desc: "AI 财务",                                   url: "https://www.stampli.com",        category: "finance", tags: ["财务"] },
  { name: "Domino",          desc: "金融 AI 平台",                              url: "https://dominodatalab.com",      category: "finance", tags: ["平台"] },

  // ---------- 天气 / 生活 ----------
  { name: "Tomorrow.io",     desc: "AI 天气",                                   url: "https://www.tomorrow.io",        category: "weather", tags: ["天气"] },
  { name: "Climacell",       desc: "天气 AI",                                   url: "https://www.tomorrow.io",        category: "weather", tags: ["天气"] },
  { name: "Replika",         desc: "AI 陪伴",                                   url: "https://replika.com",            category: "weather", tags: ["陪伴","聊天"] },
  { name: "Pi",              desc: "Inflection 情感 AI",                        url: "https://pi.ai",                  category: "weather", tags: ["情感"] },
  { name: "Character.AI",    desc: "AI 角色陪伴",                               url: "https://character.ai",          category: "weather", tags: ["角色","陪伴"] },

  // ---------- 垂直 / 小众 ----------
  { name: "Krisp",           desc: "AI 降噪",                                   url: "https://krisp.ai",               category: "niche", tags: ["降噪"] },
  { name: "Aomni",           desc: "AI 销售助手",                               url: "https://www.aomni.com",          category: "niche", tags: ["销售"] },
  { name: "Lavender",        desc: "AI 邮件教练",                               url: "https://www.lavender.ai",        category: "niche", tags: ["邮件"] },
  { name: "Superhuman AI",   desc: "AI 邮件",                                   url: "https://superhuman.com",         category: "niche", tags: ["邮件"] },
  { name: "Magical",         desc: "AI 自动填表",                               url: "https://www.getmagical.com",     category: "niche", tags: ["填表"] },
  { name: "Tome",            desc: "AI 演示",                                   url: "https://tome.app",               category: "niche", tags: ["演示"] },
  { name: "Altered",         desc: "AI 变声",                                   url: "https://www.altered.ai",         category: "niche", tags: ["变声"] },
  { name: "Voicemod",        desc: "实时变声",                                  url: "https://www.voicemod.net",       category: "niche", tags: ["变声"] },
  { name: "Lookbook AI",     desc: "AI 时尚",                                   url: "https://lookbook.ai",            category: "niche", tags: ["时尚"] },
  { name: "Vue AI",          desc: "AI 时尚零售",                               url: "https://vue.ai",                 category: "niche", tags: ["时尚"] },
  { name: "Tattoos AI",      desc: "AI 纹身设计",                               url: "https://www.tattoosai.com",      category: "niche", tags: ["纹身"] },
  { name: "RoomGPT",         desc: "AI 室内设计",                               url: "https://www.roomgpt.io",         category: "niche", tags: ["室内"] },
  { name: "ReRoom AI",       desc: "AI 室内设计",                               url: "https://reroom.ai",              category: "niche", tags: ["室内"] },
  { name: "Decor8 AI",       desc: "AI 室内",                                   url: "https://www.decor8.ai",          category: "niche", tags: ["室内"] },
  { name: "Plant Jammer",    desc: "AI 菜谱",                                   url: "https://www.plantjammer.com",    category: "niche", tags: ["菜谱"] },
  { name: "DishGen",         desc: "AI 菜谱",                                   url: "https://dishgen.com",            category: "niche", tags: ["菜谱"] },
  { name: "MealMate",        desc: "AI 饮食",                                   url: "https://www.mealmate.app",       category: "niche", tags: ["饮食"] },
  { name: "FitnessAI",       desc: "AI 健身",                                   url: "https://www.fitnessai.com",      category: "niche", tags: ["健身"] },
  { name: "Tidal",           desc: "AI 心理",                                   url: "https://www.tidal.me",           category: "niche", tags: ["心理"] },
  { name: "Woebot",          desc: "AI 心理咨询",                               url: "https://woebot.io",              category: "niche", tags: ["心理"] },
  { name: "Wysa",            desc: "AI 心理健康",                               url: "https://www.wysa.com",           category: "niche", tags: ["心理"] },

  // ============================================================
  // 第二批补录（v2 · 2025-2026 新发布 / 用户反馈遗漏）
  // ============================================================

  // ---------- AI 聊天助手：补小米 MiMo / 阶跃 / 扣子 / Genspark ----------
  { name: "Xiaomi MiMo",     desc: "小米开源 7B 推理大模型",                    url: "https://platform.xiaomimimo.com", category: "chat",  tags: ["小米","minimax","推理","国产","开源"] },
  { name: "MiMo Chat",       desc: "小米 MiMo 官方对话体验",                    url: "https://xiaomi.com/ai",          category: "chat",  tags: ["小米","minimax","国产"] },
  { name: "Genspark",        desc: "通用 AI Agent，深度搜索 + 多模型聚合",     url: "https://www.genspark.ai",        category: "chat",  tags: ["agent","搜索","多模型"] },
  { name: "Step Chat",       desc: "阶跃星辰 Step 聊天",                        url: "https://www.stepfun.com/chats/new", category: "chat", tags: ["阶跃","step","国产"] },
  { name: "腾讯 ima",        desc: "腾讯 AI 智能工作台，公众号+知识库问答",     url: "https://ima.qq.com",             category: "chat",  tags: ["腾讯","知识库","国产"] },
  { name: "千问",            desc: "阿里 Qwen Chat 官方入口",                   url: "https://www.qianwen.com",        category: "chat",  tags: ["阿里","qwen","国产"] },
  { name: "文心 5.0",        desc: "百度文心大模型 5.0，原生全模态",            url: "https://yiyan.baidu.com",        category: "chat",  tags: ["百度","文心","国产"] },
  { name: "混元",            desc: "腾讯混元大模型",                            url: "https://hunyuan.tencent.com",    category: "chat",  tags: ["腾讯","混元","国产"] },
  { name: "Z.ai",            desc: "智谱 Z.ai，对话 + 编程 + Agent",            url: "https://z.ai",                   category: "chat",  tags: ["智谱","glm","国产"] },

  // ---------- 开源模型：补小米 MiMo 全系列 ----------
  { name: "MiMo-7B",         desc: "小米开源 7B 推理模型",                      url: "https://github.com/XiaomiMiMo",  category: "opensource", tags: ["小米","minimax","推理","开源","7b"] },
  { name: "MiMo-V2-Flash",   desc: "小米 MoE 309B/激活 15B，性价比极高",        url: "https://huggingface.co/XiaomiMiMo", category: "opensource", tags: ["小米","minimax","moe","开源"] },
  { name: "MiMo-V2-Pro",     desc: "小米旗舰，万亿参数 + 1M 上下文",            url: "https://platform.xiaomimimo.com", category: "opensource", tags: ["小米","minimax","旗舰","长上下文"] },
  { name: "MiMo-V2-Omni",    desc: "小米全模态模型（文本/视觉/音频）",          url: "https://platform.xiaomimimo.com", category: "opensource", tags: ["小米","minimax","全模态","多模态"] },
  { name: "MiMo-V2-TTS",     desc: "小米端到端语音合成，支持方言+唱歌",         url: "https://platform.xiaomimimo.com", category: "opensource", tags: ["小米","minimax","tts","语音"] },
  { name: "MiMo-V2.5",       desc: "小米 MiMo V2.5 升级版",                    url: "https://github.com/XiaomiMiMo",  category: "opensource", tags: ["小米","minimax","开源","代理"] },
  { name: "Qwen3-Max-Thinking", desc: "阿里 Qwen3 旗舰推理模型",                  url: "https://huggingface.co/Qwen",     category: "opensource", tags: ["阿里","qwen","推理","开源"] },
  { name: "Qwen3-Coder-Next", desc: "阿里 Qwen3 编程专用 MoE",                  url: "https://huggingface.co/Qwen",     category: "opensource", tags: ["阿里","qwen","编程","开源"] },
  { name: "Qwen3-ASR",       desc: "阿里 Qwen3 语音识别（52种语言）",           url: "https://huggingface.co/Qwen",     category: "opensource", tags: ["阿里","qwen","asr","语音","开源"] },
  { name: "Qwen3-TTS",       desc: "阿里 Qwen3 语音生成，支持克隆",             url: "https://huggingface.co/Qwen",     category: "opensource", tags: ["阿里","qwen","tts","语音","开源"] },
  { name: "Qwen-Image-2512", desc: "阿里 Qwen-Image 2512 图像生成",             url: "https://www.modelscope.cn/models/Qwen/Qwen-Image-2512", category: "opensource", tags: ["阿里","qwen","图像","开源"] },
  { name: "Z-Image",         desc: "阿里通义 Z-Image 开源绘画",                  url: "https://huggingface.co/Tongyi-MAI/Z-Image", category: "opensource", tags: ["阿里","图像","开源"] },
  { name: "GLM-Image",       desc: "智谱 GLM-Image 图像模型，汉字生成强",       url: "https://huggingface.co/zai-org/GLM-Image", category: "opensource", tags: ["智谱","glm","图像","开源"] },
  { name: "GLM-4.7",         desc: "智谱 GLM-4.7 编码 + Agent",                  url: "https://huggingface.co/THUDM",    category: "opensource", tags: ["智谱","glm","开源"] },
  { name: "Intern-S1-Pro",   desc: "上海 AI Lab 万亿科学多模态大模型",          url: "https://chat.intern-ai.org.cn",  category: "opensource", tags: ["上海ai lab","开源","科学"] },
  { name: "Step 3.5 Flash",  desc: "阶跃星辰开源推理模型，专为 Agent",         url: "https://huggingface.co/stepfun-ai", category: "opensource", tags: ["阶跃","step","推理","开源"] },
  { name: "Step3-VL-10B",    desc: "阶跃星辰开源 10B 多模态模型",               url: "https://huggingface.co/stepfun-ai/Step3-VL-10B", category: "opensource", tags: ["阶跃","step","多模态","开源"] },
  { name: "Step-Audio-R1.1", desc: "阶跃星辰开源语音推理模型",                  url: "https://huggingface.co/stepfun-ai/Step-Audio-R1.1", category: "opensource", tags: ["阶跃","step","语音","开源"] },
  { name: "Hunyuan-Large",   desc: "腾讯混元 Large MoE 开源",                   url: "https://github.com/Tencent/Hunyuan-Large", category: "opensource", tags: ["腾讯","混元","moe","开源"] },
  { name: "HunyuanImage 3.0", desc: "腾讯混元图像 3.0",                           url: "https://hunyuan.tencent.com/visual", category: "opensource", tags: ["腾讯","混元","图像","开源"] },
  { name: "Hunyuan3D-1.0",   desc: "腾讯混元 3D 生成大模型",                      url: "https://3d.hunyuan.tencent.com",  category: "opensource", tags: ["腾讯","混元","3d","开源"] },
  { name: "Tencent-HY-MT1.5", desc: "腾讯混元翻译模型（33 语种）",               url: "https://hunyuan.tencent.com/llm", category: "opensource", tags: ["腾讯","翻译","开源"] },
  { name: "Wan 2.1 / 2.6",   desc: "阿里通义万相视频模型（开源）",              url: "https://github.com/Wan-Video",   category: "opensource", tags: ["阿里","万相","视频","开源"] },
  { name: "DeepSeek-V3.2",   desc: "DeepSeek V3.2，推理+Agent 融合",            url: "https://github.com/deepseek-ai", category: "opensource", tags: ["deepseek","推理","开源"] },
  { name: "DeepSeek-OCR 2",  desc: "DeepSeek 开源文档识别",                      url: "https://github.com/deepseek-ai/DeepSeek-OCR", category: "opensource", tags: ["deepseek","ocr","开源"] },
  { name: "Kimi K2.5",       desc: "月之暗面 K2.5，Agent 集群",                  url: "https://huggingface.co/moonshotai", category: "opensource", tags: ["kimi","moonshot","开源","代理"] },

  // ---------- 视频生成：补 2025-2026 新款 ----------
  { name: "Sora 2",          desc: "OpenAI Sora 2，音视一体 + 数字分身",        url: "https://sora.chatgpt.com",       category: "video", tags: ["openai","sora","视频","数字分身"] },
  { name: "Veo 3.1",         desc: "谷歌 Veo 3.1，音视同出 + 免费 10 段/月",   url: "https://gemini.google.com/app",  category: "video", tags: ["google","veo","视频","免费"] },
  { name: "Seedance 2.0",    desc: "字节 Seedance 2.0，多镜头 + 原生音频",     url: "https://jimeng.jianying.com",    category: "video", tags: ["字节","seedance","视频"] },
  { name: "Seed 1.8",        desc: "字节 Seed 1.8 Agent 视频模型",              url: "https://www.volcengine.com",     category: "video", tags: ["字节","seed","代理","视频"] },
  { name: "可灵 3.0",        desc: "快手可灵 3.0，多模态原生创作",              url: "https://app.klingai.com/cn/",    category: "video", tags: ["快手","可灵","视频"] },
  { name: "PixVerse V6",     desc: "爱诗 PixVerse V6，多镜头 + 音视协同",       url: "https://realtime.pixverse.ai",   category: "video", tags: ["pixverse","视频","多镜头"] },
  { name: "Vidu Q3 Pro",     desc: "生数 Vidu Q3，16s 音视频 + 漫剧友好",       url: "https://www.vidu.cn",            category: "video", tags: ["生数","vidu","视频","漫剧"] },
  { name: "Wan 2.6",         desc: "阿里通义万相 2.6，音视同步 + 角色扮演",     url: "https://tongyi.aliyun.com/wanxiang", category: "video", tags: ["阿里","万相","视频"] },
  { name: "Luma Ray 3",      desc: "Luma Ray 3，物理模拟 + HDR",                 url: "https://lumalabs.ai/ray",        category: "video", tags: ["luma","ray","视频"] },
  { name: "小云雀",          desc: "字节小云雀 AI 视频 Agent",                  url: "https://www.volcengine.com",     category: "video", tags: ["字节","agent","视频"] },
  { name: "HappyHorse 1.0",  desc: "阿里淘天 HappyHorse 音视频联合生成",        url: "https://huggingface.co/alibaba-pai", category: "video", tags: ["阿里","happyhorse","开源","视频"] },
  { name: "Hailuo 2.3",      desc: "MiniMax 海螺 2.3，文/图生视频",             url: "https://hailuoai.com",           category: "video", tags: ["minimax","海螺","视频"] },
  { name: "Medeo",           desc: "AI 视频 Agent，一键脚本到成片",             url: "https://medeo.ai",               category: "video", tags: ["agent","视频"] },
  { name: "Oiioii",          desc: "AI 视频生成 Agent",                          url: "https://oiioii.ai",              category: "video", tags: ["agent","视频"] },
  { name: "TapNow",          desc: "AI 视频 Agent 工作流",                       url: "https://tapnow.ai",              category: "video", tags: ["agent","视频","工作流"] },
  { name: "NemoVideo",       desc: "字节 NemoVideo 智能视频剪辑",               url: "https://www.volcengine.com",     category: "video", tags: ["字节","剪辑","代理"] },

  // ---------- 音频 / 音乐：补 ----------
  { name: "Suno 5",          desc: "Suno 5，可生成 4 分钟完整歌曲",             url: "https://suno.com",               category: "audio", tags: ["suno","作曲","最长"] },
  { name: "Mureka V8",       desc: "昆仑天工 Mureka V8，国产最强音乐模型",      url: "https://www.mureka.cn",          category: "audio", tags: ["昆仑","mureka","音乐","国产"] },
  { name: "海绵音乐",        desc: "字节海绵音乐 AI 作曲",                      url: "https://www.haimianmusic.com",   category: "audio", tags: ["字节","作曲","国产"] },
  { name: "IndexTTS",        desc: "B 站开源 TTS，8 种情绪控制",                url: "https://github.com/index-tts/index-tts", category: "audio", tags: ["开源","tts","语音克隆"] },
  { name: "Kimi Audio",      desc: "月之暗面 Kimi Audio 语音",                  url: "https://www.kimi.com",           category: "audio", tags: ["kimi","moonshot","音频"] },
  { name: "MusicFX",         desc: "谷歌 MusicFX 音乐生成",                     url: "https://aitestkitchen.withgoogle.com", category: "audio", tags: ["google","音乐"] },
  { name: "ListenHub",       desc: "AI 一键生成播客/解说/视频",                 url: "https://listenhub.ai",           category: "audio", tags: ["播客","音频","国产"] },

  // ---------- 图像生成：补 2025-2026 新款 ----------
  { name: "Seedream 5.0",    desc: "字节即梦 5.0，2K + 联网 + 编辑",            url: "https://jimeng.jianying.com",    category: "image", tags: ["字节","即梦","绘画"] },
  { name: "Z-Image 线上",    desc: "阿里 Z-Image 官方在线体验",                 url: "https://tongyi.aliyun.com",     category: "image", tags: ["阿里","z-image","绘画"] },
  { name: "Vega AI",         desc: "国产 AI 绘画 + 在线训练",                    url: "https://vegaai.net",             category: "image", tags: ["国产","绘画"] },
  { name: "海艺 AI",         desc: "国产 AI 绘画，12000+ 风格",                  url: "https://www.haiyi.art",          category: "image", tags: ["国产","绘画"] },
  { name: "360 鸿图",        desc: "360 AI 绘画，多风格支持",                    url: "https://aihongtu.com",           category: "image", tags: ["360","国产","绘画"] },
  { name: "稿定 AI",         desc: "稿定 AI 绘画 + 商品图",                      url: "https://www.gaoding.com",        category: "image", tags: ["稿定","国产","绘画"] },
  { name: "LiblibAI",        desc: "哩布哩布 AI，国产 SD 模型社区",             url: "https://www.liblib.art",         category: "image", tags: ["国产","sd","社区"] },
  { name: "可图 (Kling Image)", desc: "快手可图，AI 绘画 + 商品图",              url: "https://klingai.com/image",      category: "image", tags: ["快手","国产","绘画"] },
  { name: "Vheer",           desc: "在线 AI 图像生成",                           url: "https://vheer.com",              category: "image", tags: ["在线","绘画"] },
  { name: "Dzine AI",        desc: "AI 图像生成 + 编辑",                          url: "https://www.dzine.ai",           category: "image", tags: ["图像","编辑"] },
  { name: "GPT Image 1.5",   desc: "OpenAI 图像生成 1.5",                        url: "https://chatgpt.com",            category: "image", tags: ["openai","gpt-image","图像"] },
  { name: "Nano Banana Pro", desc: "谷歌最强生图（需 Gemini 会员）",            url: "https://aistudio.google.com",    category: "image", tags: ["google","nano","香蕉","生图"] },
  { name: "Remini",          desc: "AI 老照片修复 + 增强",                       url: "https://remini.ai",              category: "image", tags: ["修复","增强"] },
  { name: "Dora AI",         desc: "AI 生成 3D 网站",                            url: "https://www.dora.run",           category: "image", tags: ["3d","网站","dora"] },
  { name: "Lumiere3D",       desc: "AI 电影质感 3D 视频",                        url: "https://www.lumiere3d.ai",      category: "image", tags: ["3d","视频"] },
  { name: "即时设计",        desc: "国产在线设计 + AI 插件",                     url: "https://js.design",              category: "image", tags: ["国产","设计","插件"] },

  // ---------- 编程：补 2025-2026 IDE ----------
  { name: "TRAE",            desc: "字节 AI 原生 IDE（中文友好）",                url: "https://www.trae.cn",            category: "code",  tags: ["字节","trae","ide","国产","免费"] },
  { name: "Codebuddy",       desc: "腾讯云 Codebuddy，氛围编程 + MCP 生态",      url: "https://www.codebuddy.cn",       category: "code",  tags: ["腾讯","ide","国产"] },
  { name: "Qoder",           desc: "阿里 Qoder，AI 自主研发",                    url: "https://qoder.com",              category: "code",  tags: ["阿里","qoder","ide","国产"] },
  { name: "秒哒",            desc: "百度秒哒，一句话生成应用",                  url: "https://www.miaoda.cn",          category: "code",  tags: ["百度","无代码","国产"] },
  { name: "Antigravity",     desc: "谷歌 AI IDE，可白嫖 Gemini/Claude",          url: "https://antigravity.google",     category: "code",  tags: ["google","ide","免费"] },
  { name: "Codex",           desc: "OpenAI Codex 编程模型",                      url: "https://openai.com/codex",       category: "code",  tags: ["openai","codex"] },
  { name: "Gemini CLI",      desc: "谷歌 Gemini 命令行编程",                     url: "https://github.com/google-gemini/gemini-cli", category: "code", tags: ["google","cli"] },
  { name: "GLM Coding",      desc: "智谱 GLM Coding Plan",                       url: "https://www.bigmodel.cn/glm-coding", category: "code", tags: ["智谱","glm","国产"] },
  { name: "文心快码",        desc: "百度文心快码 Comate",                         url: "https://comate.baidu.com",       category: "code",  tags: ["百度","comate","国产"] },
  { name: "快马",            desc: "国产 AI 编程平台（自然语言生成项目）",       url: "https://www.inscode.net",        category: "code",  tags: ["国产","编程"] },
  { name: "Kimi Code",       desc: "Kimi 编程 IDE",                              url: "https://www.kimi.com/code",      category: "code",  tags: ["kimi","moonshot","国产"] },
  { name: "Blackbox AI",     desc: "AI 代码补全 + 搜索",                          url: "https://www.blackbox.ai",        category: "code",  tags: ["代码","搜索"] },
  { name: "Cline",           desc: "VSCode 开源 AI 代理",                        url: "https://github.com/cline/cline", category: "code",  tags: ["vscode","开源","代理"] },
  { name: "Roo Code",        desc: "VSCode 开源 AI 编程代理",                    url: "https://roocode.com",            category: "code",  tags: ["vscode","开源","代理"] },
  { name: "KiloCode",        desc: "AI 编程代理（免费模型）",                    url: "https://kilocode.ai",            category: "code",  tags: ["代理","免费"] },
  { name: "OpenHands",       desc: "开源 AI 软件工程师",                          url: "https://github.com/All-Hands-AI/OpenHands", category: "code", tags: ["开源","代理"] },

  // ---------- 设计：补 Agent 类 ----------
  { name: "Lovart",          desc: "设计 Agent 标杆，集成所有主流生图/视频",     url: "https://lovart.ai",              category: "design", tags: ["agent","设计","顶级"] },
  { name: "星流 Xingliu",    desc: "国产设计 Agent",                              url: "https://www.xingliu.art",        category: "design", tags: ["agent","设计","国产"] },
  { name: "Remini 设计",     desc: "AI 增强 / 老照片修复",                        url: "https://remini.ai",              category: "design", tags: ["设计","增强"] },
  { name: "DailyTech AI",    desc: "AI 全场景设计（网页/视频/广告）",            url: "https://dailytech.ai",           category: "design", tags: ["设计","全场景"] },

  // ---------- AI 智能体：补 2025-2026 ----------
  { name: "扣子 Coze 2.0",   desc: "字节扣子 2.0，Skills 智能体平台",            url: "https://www.coze.cn",            category: "agent", tags: ["字节","扣子","国产","skills"] },
  { name: "Dify",            desc: "开源 LLM 应用开发平台",                      url: "https://dify.ai",                category: "agent", tags: ["开源","编排"] },
  { name: "FastGPT",         desc: "国产开源 Agent 知识库平台",                  url: "https://fastgpt.io/zh",          category: "agent", tags: ["国产","开源","知识库"] },
  { name: "Kimi Agent",      desc: "Kimi 深度研究 + Agent",                      url: "https://www.kimi.com",           category: "agent", tags: ["kimi","国产","深度研究"] },
  { name: "Kimi ok Computer", desc: "Kimi 一键生成应用/PPT",                     url: "https://www.kimi.com/ok-computer", category: "agent", tags: ["kimi","应用","国产"] },
  { name: "Skywork 桌面版",  desc: "昆仑天工 Skywork 桌面 AI Agent",             url: "https://skywork.ai/desktop",     category: "agent", tags: ["昆仑","skywork","国产"] },
  { name: "Skywork 网页版",  desc: "Skywork 网页版",                              url: "https://skywork.ai",             category: "agent", tags: ["skywork","昆仑","国产"] },
  { name: "Claude Cowork",   desc: "Anthropic Claude Cowork，桌面 Agent",         url: "https://claude.com",             category: "agent", tags: ["claude","cowork","桌面"] },
  { name: "OpenClaw",        desc: "开源 AI 助手网关（WhatsApp/Telegram）",       url: "https://openclaw.ai",            category: "agent", tags: ["开源","代理"] },
  { name: "AutoGLM",         desc: "智谱 AI 手机 Agent",                          url: "https://chatglm.cn",             category: "agent", tags: ["智谱","手机","代理","国产"] },
  { name: "Step Agent",      desc: "阶跃星辰 Step-GUI 端侧 Agent",               url: "https://github.com/stepfun-ai",  category: "agent", tags: ["阶跃","step","代理","国产"] },
  { name: "Mistral Agents",  desc: "Mistral 智能体平台",                          url: "https://docs.mistral.ai",        category: "agent", tags: ["mistral","代理"] },
  { name: "Manus",           desc: "通用 AI Agent",                               url: "https://manus.im",               category: "agent", tags: ["agent","通用"] },
  { name: "Devin",           desc: "Cognition AI 软件工程师",                    url: "https://www.cognition.ai",      category: "agent", tags: ["agent","devin"] },
  { name: "Bolt.new",        desc: "StackBlitz AI 全栈生成",                    url: "https://bolt.new",               category: "agent", tags: ["全栈","web"] },
  { name: "Lovable",         desc: "AI 全栈 Web 生成",                           url: "https://lovable.dev",            category: "agent", tags: ["全栈","web"] },

  // ---------- AI 搜索：补 ----------
  { name: "夸克",            desc: "阿里夸克，AI 超级框 + 深度搜索",             url: "https://www.quark.cn",           category: "search", tags: ["阿里","国产","搜索"] },
  { name: "秘塔 AI 搜索",    desc: "国产 AI 搜索，深耕多年",                     url: "https://metaso.cn",              category: "search", tags: ["秘塔","国产","搜索"] },
  { name: "腾讯 ima 搜索",   desc: "腾讯 ima 知识库 + 公众号搜索",               url: "https://ima.qq.com",             category: "search", tags: ["腾讯","国产","搜索"] },
  { name: "微信 AI 搜索",    desc: "微信内置 AI 搜索",                            url: "https://weixin.qq.com",          category: "search", tags: ["微信","国产","搜索"] },
  { name: "Felo",            desc: "AI 搜索引擎",                                 url: "https://felo.ai",                category: "search", tags: ["搜索","felo"] },

  // ---------- AI 浏览器（新分类）----------
  { name: "Dia Browser",     desc: "全球首个 AI 原生浏览器",                     url: "https://www.diabrowser.com",     category: "browser", tags: ["浏览器","ai原生"] },
  { name: "ChatGPT Atlas",   desc: "OpenAI AI 浏览器",                            url: "https://openai.com/atlas",       category: "browser", tags: ["openai","浏览器"] },
  { name: "Perplexity Comet", desc: "Perplexity AI 浏览器",                       url: "https://comet.perplexity.ai",    category: "browser", tags: ["perplexity","浏览器"] },
  { name: "Arc Browser",     desc: "Arc 浏览器（内置 AI）",                       url: "https://arc.net",                category: "browser", tags: ["arc","浏览器"] },
  { name: "360 AI 浏览器",   desc: "360 极速浏览器 AI 版",                       url: "https://browser.360.cn",         category: "browser", tags: ["360","国产","浏览器"] },

  // ---------- 会议 / 笔记：补 ----------
  { name: "Get 笔记",        desc: "得到 App 出的 AI 笔记 + 录音",                url: "https://www.biji.com",           category: "meeting", tags: ["得到","笔记","录音"] },
  { name: "YouMind",         desc: "玉伯的 AI 剪藏 + 知识库",                    url: "https://youmind.com",            category: "meeting", tags: ["剪藏","知识库"] },
  { name: "ChatMemo",        desc: "AI 对话统一管理（跨平台）",                  url: "https://chatmemo.ai",            category: "meeting", tags: ["对话","管理"] },
  { name: "NotebookLM",      desc: "Google 笔记 + 播客生成",                      url: "https://notebooklm.google.com",  category: "meeting", tags: ["google","笔记","播客"] },
  { name: "AI 录音豆",       desc: "安克 + 飞书 AI 录音卡",                       url: "https://www.anker.com",          category: "meeting", tags: ["安克","飞书","录音"] },

  // ---------- PPT：补 ----------
  { name: "GenFlow 3.0",     desc: "百度文库 GenFlow，AI 深度做 PPT",            url: "https://wenku.baidu.com",        category: "ppt",    tags: ["百度","文库","国产"] },
  { name: "AIPPT.cn",        desc: "国产 AI PPT 平台",                            url: "https://www.aippt.cn",           category: "ppt",    tags: ["国产","ppt"] },
  { name: "Kimi Slides",     desc: "Kimi 海外版 PPT（带图片）",                   url: "https://www.kimi.com/slides",    category: "ppt",    tags: ["kimi","国产","ppt"] },

  // ---------- AI 数字人（新分类）----------
  { name: "蝉镜",            desc: "数字人短视频，性价比高",                     url: "https://www.chanmirror.com",     category: "digitalhuman", tags: ["数字人","国产"] },
  { name: "百度慧播星",     desc: "百度数字人平台",                              url: "https://huibox.baidu.com",       category: "digitalhuman", tags: ["百度","数字人","国产"] },
  { name: "剪映数字人",      desc: "剪映内置数字人",                              url: "https://www.capcut.com",         category: "digitalhuman", tags: ["字节","剪映","数字人"] },
  { name: "HeyGen",          desc: "数字人 / 视频翻译",                           url: "https://www.heygen.com",         category: "digitalhuman", tags: ["数字人","翻译"] },
  { name: "Synthesia",       desc: "AI 数字人视频",                                url: "https://www.synthesia.io",       category: "digitalhuman", tags: ["数字人","企业"] },
  { name: "D-ID",            desc: "照片转数字人",                                url: "https://www.d-id.com",           category: "digitalhuman", tags: ["数字人","照片"] },
  { name: "Colossyan",       desc: "企业数字人",                                  url: "https://www.colossyan.com",      category: "digitalhuman", tags: ["数字人","企业"] },

  // ---------- AI 输入法（新分类）----------
  { name: "Typeless",        desc: "AI 语音输入法",                                url: "https://www.typeless.com",       category: "input",  tags: ["输入法","语音"] },
  { name: "闪电说",          desc: "国产 AI 语音输入法",                          url: "https://www.shandianshuo.com",   category: "input",  tags: ["国产","输入法","语音"] },
  { name: "豆包输入法",      desc: "字节豆包 AI 输入法",                          url: "https://shurufa.doubao.com",     category: "input",  tags: ["字节","国产","输入法"] },

  // ---------- 3D / 空间：补 ----------
  { name: "Hunyuan3D",       desc: "腾讯混元 3D",                                 url: "https://3d.hunyuan.tencent.com", category: "3d",     tags: ["腾讯","混元","3d","国产"] },
  { name: "World Labs",      desc: "李飞飞团队空间智能，一张图生成 3D 世界",     url: "https://www.worldlabs.ai",       category: "3d",     tags: ["李飞飞","空间智能","3d"] },
  { name: "Tripo3D",         desc: "AI 3D 建模",                                   url: "https://www.tripo3d.ai",         category: "3d",     tags: ["3d","建模"] },
  { name: "Meshy",           desc: "文/图转 3D",                                  url: "https://www.meshy.ai",           category: "3d",     tags: ["3d","文转3d"] },

  // ---------- 世界模型（新分类）----------
  { name: "PixVerse R1",     desc: "爱诗实时世界模型（无限流生成）",              url: "https://realtime.pixverse.ai",   category: "world",  tags: ["pixverse","世界模型","实时"] },
  { name: "Genie 2",         desc: "DeepMind 世界模型",                            url: "https://deepmind.google",        category: "world",  tags: ["deepmind","世界模型"] },
  { name: "Skybox",          desc: "Skybox 360° 世界生成",                         url: "https://skybox.blockadelabs.com", category: "world", tags: ["skybox","世界模型","360"] },

  // ---------- 数据分析：补 ----------
  { name: "Reportify",       desc: "AI 财报研报分析",                              url: "https://reportify.cc",           category: "data",   tags: ["财报","研报","金融"] },
  { name: "ChatGPT Deep Research", desc: "OpenAI 深度研究",                            url: "https://chatgpt.com",            category: "data",   tags: ["openai","深度研究"] },
  { name: "Kimi 深度研究",   desc: "Kimi 深度研究（低幻觉）",                     url: "https://www.kimi.com/deep-research", category: "data", tags: ["kimi","国产","深度研究"] },

  // ---------- 写作：补 ----------
  { name: "讯飞绘文",        desc: "讯飞 AI 写作 + GEO 一键发布",                 url: "https://turbodesk.xfyun.cn",     category: "writing", tags: ["讯飞","国产","写作","geo"] },
  { name: "Napkin",          desc: "文字转可视化图表",                             url: "https://www.napkin.ai",          category: "writing", tags: ["写作","可视化"] },

  // ---------- 营销：补 ----------
  { name: "Murf",            desc: "AI 配音 / 数字人",                             url: "https://murf.ai",                category: "marketing", tags: ["配音","数字人"] },

  // ---------- 翻译：补（Tencent-HY-MT 已在 opensource）----------
  { name: "DeepL Write",     desc: "DeepL 推出的 AI 写作助手",                    url: "https://www.deepl.com/write",    category: "writing", tags: ["deepl","写作"] },

  // ---------- 垂直 / 小众：补 ----------
  { name: "朱雀",            desc: "腾讯 AIGC 内容检测",                          url: "https://matrix.tencent.com/ai-detect", category: "niche", tags: ["腾讯","检测","国产"] },
  { name: "Originality.ai",  desc: "AI 内容检测",                                  url: "https://originality.ai",         category: "niche",  tags: ["检测","英文"] },
  { name: "Pictory",         desc: "文转视频",                                     url: "https://pictory.ai",             category: "niche",  tags: ["文转视频"] },
  { name: "Steve AI",        desc: "动画视频生成",                                 url: "https://www.steve.ai",           category: "niche",  tags: ["动画"] },
  { name: "Lumen5",          desc: "博客转视频",                                   url: "https://lumen5.com",             category: "niche",  tags: ["博客","转视频"] },
  { name: "Fliki",           desc: "文案转带配音视频",                             url: "https://fliki.ai",               category: "niche",  tags: ["配音","文案"] },
  { name: "RoomGPT",         desc: "AI 室内设计",                                  url: "https://www.roomgpt.io",         category: "niche",  tags: ["室内"] },
  { name: "Tattoos AI",      desc: "AI 纹身设计",                                  url: "https://www.tattoosai.com",      category: "niche",  tags: ["纹身"] },

  // ============================================================
  // 第三批补录（v3 · 用户反馈"不全"再补一波）
  // ============================================================

  // ---------- AI 智能体：补飞书 aily / LobsterAI / 桌面 Agent ----------
  { name: "飞书 aily",       desc: "飞书 AI 同事，主动跟进 + 团队共享智能体",     url: "https://aily.feishu.cn",        category: "agent", tags: ["飞书","国产","团队","代理"] },
  { name: "LobsterAI",      desc: "网易有道龙虾，国内首个开源桌面级 Agent",     url: "https://lobsterai.youdao.com",  category: "agent", tags: ["网易","开源","桌面","国产"] },
  { name: "AutoClaw",       desc: "智谱本地桌面 Agent，浏览器自动化",            url: "https://autoglm.zhipuai.cn/autoclaw/", category: "agent", tags: ["智谱","国产","桌面"] },
  { name: "QClaw",          desc: "腾讯电脑管家桌面 Agent",                       url: "https://qclaw.qq.com",          category: "agent", tags: ["腾讯","国产","桌面"] },
  { name: "EasyClaw",       desc: "猎豹移动轻量桌面 Agent",                       url: "https://easyclaw.cn",           category: "agent", tags: ["猎豹","国产","桌面"] },
  { name: "QoderWork",      desc: "阿里 Qoder 桌面 AI 工作台",                    url: "https://qoder.com/zh/qoderwork", category: "agent", tags: ["阿里","国产","桌面"] },
  { name: "ArkClaw",        desc: "字节火山云端 OpenClaw 一键部署",               url: "https://www.volcengine.com/experience/ark?mode=claw", category: "agent", tags: ["字节","国产","云端"] },
  { name: "飞书秒搭",      desc: "飞书 OpenClaw 部署平台",                       url: "https://miaoda.feishu.cn/bot",  category: "agent", tags: ["飞书","国产","云端"] },
  { name: "MaxClaw",        desc: "MiniMax 云端 OpenClaw 平台",                    url: "https://agent.minimaxi.com/max-claw", category: "agent", tags: ["minimax","云端","国产"] },
  { name: "Kimi Claw",      desc: "Kimi 云端 OpenClaw 部署",                       url: "https://www.kimi.com/bot",      category: "agent", tags: ["kimi","云端","国产"] },
  { name: "AstronClaw",     desc: "科大讯飞云端 Agent 平台",                      url: "https://agent.xfyun.cn/astron-claw", category: "agent", tags: ["讯飞","云端","国产"] },
  { name: "煎蛋智能体",    desc: "零代码企业级 AI 智能体平台",                  url: "https://www.gendial.cn",         category: "agent", tags: ["企业","零代码","国产"] },
  { name: "Astron Agent",   desc: "科大讯飞 AstronClaw 全栈国产化平台",           url: "https://agent.xfyun.cn",         category: "agent", tags: ["讯飞","国产","企业"] },
  { name: "盘古 AI Agent",  desc: "华为盘古工业级 AI Agent",                       url: "https://www.huaweicloud.com/product/pangu.html", category: "agent", tags: ["华为","工业","国产"] },
  { name: "通义千问 Agent", desc: "阿里通义千问电商内容 Agent",                  url: "https://qianwen.aliyun.com",    category: "agent", tags: ["阿里","电商","国产"] },
  { name: "豆包企业 Agent", desc: "字节豆包企业版轻量 Agent",                    url: "https://www.volcengine.com",     category: "agent", tags: ["字节","国产","企业"] },
  { name: "AgentBox",       desc: "星环科技企业智能体开发平台",                  url: "https://www.transwarp.cn",       category: "agent", tags: ["企业","国产","开发"] },
  { name: "AI-Agentforce",  desc: "迈富时企业级智能体中台",                       url: "https://www.maifushi.com",      category: "agent", tags: ["企业","国产"] },

  // ---------- 聊天助手：补千问 App / 阶跃 / 橙篇 / 一些国产 ----------
  { name: "千问 App",       desc: "阿里千问 App（点外卖+购物+订机票）",          url: "https://app.qianwen.com",       category: "chat",  tags: ["阿里","国产","app"] },
  { name: "Step Chat 网页", desc: "阶跃星辰 Step 网页版聊天",                    url: "https://www.stepfun.com",       category: "chat",  tags: ["阶跃","国产"] },
  { name: "橙篇",           desc: "百度橙篇，AI 长文创作",                        url: "https://chengpian.baidu.com",  category: "chat",  tags: ["百度","国产","长文"] },
  { name: "当贝 AI",        desc: "满血版 DeepSeek，免注册免费",                 url: "https://www.dangbei.com/ai",    category: "chat",  tags: ["deepseek","国产","免费"] },
  { name: "搜狐简单 AI",    desc: "搜狐简单 AI，绘画/头像/海报/文案",            url: "https://ai.sohu.com",           category: "chat",  tags: ["国产","绘画","文案"] },
  { name: "腾讯 Effidit",   desc: "腾讯智能创作助手，纠错+脑图",                 url: "https://effidit.qq.com",        category: "chat",  tags: ["腾讯","国产","写作"] },
  { name: "讯飞星火",      desc: "科大讯飞星火认知大模型",                       url: "https://xinghuo.xfyun.cn",     category: "chat",  tags: ["讯飞","国产"] },
  { name: "华为小艺",      desc: "华为 AI 智慧助手",                              url: "https://xiaoyi.huawei.com",     category: "chat",  tags: ["华为","国产"] },
  { name: "Tldraw",         desc: "AI 绘图白板 / 草图转 UI",                       url: "https://www.tldraw.com",        category: "image", tags: ["白板","草图"] },
  { name: "PicsArt",        desc: "AI 编辑 + 拼贴 + 绘画",                         url: "https://picsart.com",           category: "image", tags: ["编辑","绘画"] },

  // ---------- 编程：补 Kiro/Zed/Replit/Sourcegraph/Aider 等 ----------
  { name: "Kiro",           desc: "AWS AI IDE",                                   url: "https://kiro.dev",              category: "code",  tags: ["aws","ide"] },
  { name: "Zed",            desc: "Atom 团队高性能 AI 编辑器",                    url: "https://zed.dev",               category: "code",  tags: ["编辑器","高性能"] },
  { name: "Replit",         desc: "Replit 云端 IDE + Ghostwriter",                 url: "https://replit.com",            category: "code",  tags: ["replit","ide","云端"] },
  { name: "Sourcegraph",    desc: "代码智能搜索 + Cody",                           url: "https://sourcegraph.com",       category: "code",  tags: ["代码搜索","cody"] },
  { name: "Aider",          desc: "开源终端 AI 编程助手",                          url: "https://aider.chat",            category: "code",  tags: ["终端","开源"] },
  { name: "JetBrains AI",   desc: "JetBrains IDE 内置 AI",                        url: "https://www.jetbrains.com/ai",  category: "code",  tags: ["jetbrains","ide"] },
  { name: "Augment Code",   desc: "企业级 AI 编程",                                  url: "https://www.augmentcode.com",   category: "code",  tags: ["企业","ide"] },
  { name: "Codex CLI",      desc: "OpenAI Codex 命令行版",                         url: "https://github.com/openai/codex", category: "code", tags: ["openai","cli"] },
  { name: "OpenCode",       desc: "开源终端 AI Agent",                              url: "https://opencode.ai",           category: "code",  tags: ["终端","开源"] },
  { name: "Pythagora",      desc: "AI 全栈开发（14 个 Agent）",                    url: "https://www.pythagora.ai",      category: "code",  tags: ["全栈","代理"] },
  { name: "SoftGen",        desc: "AI 全栈 Web 应用生成",                          url: "https://www.softgen.ai",        category: "code",  tags: ["全栈","web"] },

  // ---------- 设计：补 Pomelli / Google Stitch ----------
  { name: "Pomelli",        desc: "Google Labs 品牌设计 AI",                       url: "https://pomelli.withgoogle.com", category: "design", tags: ["google","品牌","设计"] },
  { name: "Google Stitch",  desc: "谷歌 Stitch UI 设计（前 Galileo AI）",         url: "https://stitch.withgoogle.com", category: "design", tags: ["google","ui","设计"] },
  { name: "Magic Patterns", desc: "AI UI 组件生成",                                url: "https://www.magicpatterns.com", category: "design", tags: ["ui","组件"] },
  { name: "Relume",         desc: "AI 帮你搭线框图",                                url: "https://www.relume.io",         category: "design", tags: ["线框图","figma"] },

  // ---------- 搜索：补 AnySearch / Brave / Kagi / 微信 ----------
  { name: "AnySearch",      desc: "智能体搜索（垂直/多源/结构化）",               url: "https://anysearch.ai",          category: "search", tags: ["智能体","搜索","api"] },
  { name: "Brave Search",   desc: "Brave 隐私搜索 API",                            url: "https://brave.com/search/api",  category: "search", tags: ["brave","隐私","api"] },
  { name: "Kagi",           desc: "付费无广告 AI 搜索",                            url: "https://kagi.com",              category: "search", tags: ["付费","无广告"] },
  { name: "Felo",           desc: "AI 搜索引擎",                                   url: "https://felo.ai",               category: "search", tags: ["搜索"] },
  { name: "微信 AI 搜索",  desc: "微信内置 AI 搜索",                              url: "https://weixin.qq.com",         category: "search", tags: ["微信","国产","搜索"] },

  // ---------- 音频：补易魔声 / 一些 ----------
  { name: "易魔声",         desc: "网易有道开源 TTS，2000+ 音色",                 url: "https://github.com/netease-youdao/EmotiVoice", category: "audio", tags: ["网易","开源","tts","国产"] },

  // ---------- 3D / 世界模型：补 World Labs / Genie 2 / Skybox ----------
  { name: "World Labs",     desc: "李飞飞团队空间智能，一张图生成 3D 世界",      url: "https://www.worldlabs.ai",      category: "3d",     tags: ["李飞飞","空间智能","3d"] },
  { name: "Genie 2",        desc: "DeepMind 世界模型",                             url: "https://deepmind.google",       category: "world",  tags: ["deepmind","世界模型"] },
  { name: "Skybox",         desc: "Skybox 360° 世界生成",                          url: "https://skybox.blockadelabs.com", category: "world", tags: ["skybox","世界模型","360"] },

  // ---------- 研究/数据：补 Wolfram / Reportify ----------
  { name: "Wolfram Alpha",  desc: "计算知识引擎 / AI 驱动",                        url: "https://www.wolframalpha.com",  category: "research", tags: ["计算","知识","引擎"] },
  { name: "Reportify",      desc: "AI 财报研报分析",                               url: "https://reportify.cc",          category: "data",   tags: ["财报","研报","金融"] },

  // ---------- 营销：补 ----------
  { name: "Murf",            desc: "AI 配音 / 数字人",                                url: "https://murf.ai",               category: "marketing", tags: ["配音","数字人"] },

  // ---------- 翻译：补 DeepL Write（已在 writing，避免重复）----------
  { name: "Pomelli 中文",   desc: "Pomelli 谷歌品牌设计 AI",                        url: "https://pomelli.withgoogle.com", category: "design", tags: ["google","品牌"] }
];

// 兼容性导出（防止某些环境不支持 const 数组）
if (typeof window !== "undefined") {
  window.AI_NAV = { CATEGORIES, TOOLS };
}
